import { access, copyFile, mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const mobileRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const webRoot = process.env.OPENTOPO_WEB_ROOT
  ? path.resolve(process.env.OPENTOPO_WEB_ROOT)
  : path.resolve(mobileRoot, "..", "OpenTopo");
const contentRoot = path.join(webRoot, "content", "areas");
const outputPath = path.join(mobileRoot, "src", "data", "topo.seed.json");
const assetOutputRoot = path.join(mobileRoot, "assets", "topo");
const assetRegistryPath = path.join(mobileRoot, "src", "data", "topoAssets.ts");

async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, "utf8"));
}

async function firstExisting(paths) {
  for (const candidate of paths) {
    try {
      await access(candidate);
      return candidate;
    } catch {
      // Try the next source convention used by OpenTopo content.
    }
  }
  return null;
}

function bundledRelPath(src) {
  const cleanSrc = src.replace(/^\/+/, "");
  const parsed = path.parse(cleanSrc);
  const ext = parsed.ext.toLowerCase();
  const normalizedExt = ext === ".jpeg" ? ".jpg" : ext;
  return path.join(parsed.dir, `${parsed.name}${normalizedExt}`);
}

/** Metro resolves assets case-sensitively; macOS copyFile can keep an existing .JPG name. */
async function assertExactBasename(filePath) {
  const wanted = path.basename(filePath);
  const names = await readdir(path.dirname(filePath));
  if (!names.includes(wanted)) {
    const actual = names.filter((name) => name.toLowerCase() === wanted.toLowerCase()).join(", ") || "missing";
    throw new Error(`Topo photo was stored as ${actual} instead of ${wanted}`);
  }
}

async function copyTopoPhoto(areaId, src) {
  const cleanSrc = src.replace(/^\/+/, "");
  const bundledSrc = bundledRelPath(src);
  const source = await firstExisting([
    path.join(webRoot, cleanSrc),
    path.join(webRoot, "public", cleanSrc),
    path.join(webRoot, "assets", "areas", areaId, cleanSrc),
    path.join(webRoot, "public", "assets", "areas", areaId, cleanSrc)
  ]);

  if (!source) {
    console.warn(`Missing topo photo for ${areaId}: ${src}`);
    return null;
  }

  const destination = path.join(assetOutputRoot, areaId, bundledSrc);
  await mkdir(path.dirname(destination), { recursive: true });
  const tmp = `${destination}.${process.pid}.tmp`;
  await copyFile(source, tmp);
  await rename(tmp, destination);
  await assertExactBasename(destination);
  return destination;
}

async function buildSeed() {
  await rm(assetOutputRoot, { recursive: true, force: true });
  await mkdir(assetOutputRoot, { recursive: true });

  const areaIds = (await readdir(contentRoot)).sort();
  const areas = [];
  const photoAssets = [];

  for (const areaId of areaIds) {
    const areaPath = path.join(contentRoot, areaId, "area.json");
    let area;
    try {
      area = await readJson(areaPath);
    } catch {
      continue;
    }

    const boulders = [];
    for (const boulderRef of area.boulders ?? []) {
      const boulder = await readJson(path.join(contentRoot, areaId, boulderRef));
      for (const photo of boulder.photos ?? []) {
        if (!photo?.src) continue;
        const destination = await copyTopoPhoto(areaId, photo.src);
        if (destination) photoAssets.push({ key: `${areaId}:${photo.src}`, destination });
      }
      boulders.push(boulder);
    }

    areas.push({ ...area, boulders });
  }

  const version = areas
    .map((area) => area.updated ?? "")
    .sort()
    .at(-1) || new Date().toISOString().slice(0, 10);
  const seed = { schemaVersion: 1, version, areas };

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, `${JSON.stringify(seed, null, 2)}\n`);

  const registryLines = photoAssets
    .sort((left, right) => left.key.localeCompare(right.key))
    .map(({ key, destination }) => {
      let relative = path.relative(path.dirname(assetRegistryPath), destination).split(path.sep).join("/");
      if (!relative.startsWith(".")) relative = `./${relative}`;
      return `  ${JSON.stringify(key)}: require(${JSON.stringify(relative)}),`;
    });
  const registry = [
    "/* Generated by scripts/sync-topo.mjs. Do not edit by hand. */",
    'import type { ImageSourcePropType } from "react-native";',
    "",
    "export const topoAssets: Record<string, ImageSourcePropType> = {",
    ...registryLines,
    "};",
    ""
  ].join("\n");
  await writeFile(assetRegistryPath, registry);

  console.log(
    `Wrote ${areas.length} areas and ${photoAssets.length} offline photos from ${contentRoot} to ${path.relative(mobileRoot, outputPath)}`
  );
}

await buildSeed();
